# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('short_name', models.CharField(db_index=True, max_length=60)),
                ('short_state', models.CharField(db_index=True, max_length=60)),
                ('long_state', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('region', models.CharField(db_index=True, max_length=40)),
                ('timezone', models.CharField(max_length=30)),
            ],
        ),
    ]
