# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geocity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('section', models.CharField(db_index=True, max_length=15)),
                ('pretty_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=60, verbose_name='email address')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('flag_message', models.CharField(choices=[(b'Inappropriate Content', b'Inappropriate or Illegal Content'), (b'Over Posted', b'Over Posted / Spam'), (b'Wrong Category', b'Wrong Category')], default='', max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedAd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=170)),
                ('body', models.TextField()),
                ('images', models.CharField(blank=True, default='', max_length=1200)),
                ('age', models.PositiveSmallIntegerField(default=21)),
                ('link', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, default='', max_length=60)),
                ('phone', models.CharField(blank=True, default='', max_length=12)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_scrapedad_city_related', to='geocity.City')),
            ],
        ),
    ]
