# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-23 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_scrapedad_city_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedad',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
