# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20170823_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedad',
            name='post_id',
            field=models.CharField(db_index=True, default='1234', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrapedad',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='scrapedad',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
