# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20170824_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportad',
            name='object_id',
            field=models.CharField(max_length=50),
        ),
    ]
