# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-29 22:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geocity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesAd',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edit_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('posted', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[(b'live', b'live'), (b'pending', b'pending'), (b'turnedoff', b'turned off'), (b'expired', b'expired'), (b'flagged', b'flagged'), (b'removedbyuser', b'removed by user'), (b'underreview', b'under review')], db_index=True, default='', max_length=15)),
                ('title', models.CharField(max_length=170)),
                ('body', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=60, verbose_name='email address')),
                ('images', models.CharField(blank=True, default='', max_length=600)),
                ('agree_to_terms', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.AdCategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_servicesad_city_related', to='geocity.City')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
